name: Dollar Bot

on:
  schedule:
    - cron: "0 */2 * * *"
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install python-telegram-bot==13.15

      - run: python bot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - run: python report.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
